language: go

go:
  - tip

install:
  - export GOPATH="$HOME/gopath"
  - mkdir -p "$GOPATH/src/golang.org/x"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/github.com/vosmith/oauth2"
  - go get -v -t -d github.com/vosmith/oauth2/...

script:
  - go test -v github.com/vosmith/oauth2/...
